### ISSUE TITLE
Line delimited GeoJSON

### ISSUE THREAD

**Issue by andrewharvey** [openaddresses/batch-machine#2]
Line delimited GeoJSON features is growing in use as it can be easier for some applications to read and write than regular GeoJSON wrapped as a FeatureCollection.

I tried feeding Line delimited GeoJSON to OpenAddresses but it failed parsing, so it would be nice to have support for this.

**Comment by missinglink** [comment]
FYI a quick'n'hacky way of converting JSON lines to a FeatureCollection:

```bash
#!/bin/bash

featureCollectionSandwich() {
  echo '{ "type": "FeatureCollection", "features":'
  cat - | jq -s .
  echo '}'
}
```

```bash
cat lines | featureCollectionSandwich
```

**Comment by andrewharvey** [comment]
I've used many hacks with cat and sed but that last trailing comma is pesky. Would jq work fine with a gigabyte size file on a small machine with little RAM? Anything that loads the whole thing into memory usually crashes for me.

**Comment by ingalls** [comment]
@andrewharvey Yes, JQ is entirely streaming, I've processed hundreds of gig files without any problem

**Comment by ingalls** [comment]
Batch Machine can now output GeoJSON+LD

Ref: https://github.com/openaddresses/batch-machine/pull/45
