### ISSUE TITLE
Don't uppercase field names for CSV sources

### ISSUE THREAD

**Issue by arch0345** [openaddresses/batch-machine#61]
Looks like we're getting bitten by a `KeyError` here again. Something in our pipeline is upper-casing CSV row names. Last time I looked at this I couldn't figure out where/why we're doing this. It involves a change to the `batch-machine` code, I think.

_Originally posted by @iandees in https://github.com/openaddresses/openaddresses/pull/7395#issuecomment-2330534957_

cc @ingalls

**Comment by skylarmt** [comment]
> Something in our pipeline is upper-casing CSV row names.

Is it https://github.com/openaddresses/batch-machine/blob/73f9e9f01d0a372633c74345e9f9a666264a48f8/openaddr/conform.py#L919, as suggested by [andrewharvey](https://github.com/andrewharvey) in https://github.com/openaddresses/openaddresses/issues/5554?

**Comment by iandees** [comment]
I believe I resolved this with #65.
